version: '3'

controller-environment: &controller-environment
      KAFKA_CFG_PROCESS_ROLES: 'controller'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@controller1:29091,2@controller2:29092,3@controller3:29093'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CFG_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_KRAFT_CLUSTER_ID: 'eqzumUc5SUii2QiSB9jBWA'

broker-environment: &broker-environment
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@controller1:29091,2@controller2:29092,3@controller3:29093'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_PROCESS_ROLES: 'broker'
      KAFKA_CFG_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_KRAFT_CLUSTER_ID: 'eqzumUc5SUii2QiSB9jBWA'
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3 
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 3

services:
  controller1:
    image:  bitnami/kafka:3.5-debian-11
    container_name: controller1
    hostname: controller1
    ports:
      - "9091:9091"
      - "29091:29091"
    environment:
      <<: *controller-environment
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: 'CONTROLLER://controller1:29091'

  controller2:
    image:  bitnami/kafka:3.5-debian-11
    container_name: controller2
    hostname: controller2
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      <<: *environment
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_LISTENERS: 'CONTROLLER://controller2:29092'

  controller3:
    image:  bitnami/kafka:3.5-debian-11
    container_name: controller3
    hostname: controller3
    ports:
      - "9093:9093"
      - "29093:29093"
    environment:
      <<: *environment
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_LISTENERS: 'CONTROLLER://controller3:29093'

  kafka1:
    image: bitnami/kafka:3.5-debian-11
    container_name: kafka1
    hostname: kafka1
    depends_on:
      - controller1
      - controller2
      - controller3
    ports:
      - "9094:9094"
      - "29094:29094"
    environment:
      <<: *broker-environment
      KAFKA_CFG_NODE_ID: 4
      KAFKA_CFG_BROKER_ID: 4
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://kafka1:29094,EXTERNAL://:9094'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:29094,EXTERNAL://192.168.88.239:9094'


  kafka2:
    image: bitnami/kafka:3.5-debian-11
    container_name: kafka2
    hostname: kafka2
    depends_on:
      - controller1
      - controller2
      - controller3
    ports:
      - "9095:9095"
      - "29095:29095"
    environment:
      <<: *broker-environment
      KAFKA_CFG_NODE_ID: 5
      KAFKA_CFG_BROKER_ID: 5
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://kafka2:29095,EXTERNAL://:9095'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:29095,EXTERNAL://192.168.88.239:9095'

  kafka3:
    image: bitnami/kafka:3.5-debian-11
    container_name: kafka3
    hostname: kafka3
    depends_on:
      - controller1
      - controller2
      - controller3
    ports:
      - "9096:9096"
      - "29096:29096"
    environment:
      <<: *broker-environment
      KAFKA_CFG_NODE_ID: 6
      KAFKA_CFG_BROKER_ID: 6
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://kafka3:29096,EXTERNAL://:9096'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka3:29096,EXTERNAL://192.168.88.239:9096'

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=controller1:9091,controller2:9092,controller3:9093,kafka1:29094,kafka1:29095,kafka1:29096
